### ISSUE TITLE
Compilation problem with test_vicon2_driver

### ISSUE THREAD

**Issue by evbernardes** [MOCAP4ROS2-Project/mocap4ros2_vicon#6]
When I tried to compile the project, I had the following problem:

> --- stderr: vicon2_driver                             
/home/evbernardes/ros2_ws/src/vicon2_driver/test/test_vicon2_driver.cpp: In member function ‘virtual void UtilsTest_test_vicon2_params_Test::TestBody()’:
/home/evbernardes/ros2_ws/src/vicon2_driver/test/test_vicon2_driver.cpp:83:56: error: ‘rclcpp::executor’ has not been declared
   83 |   rclcpp::executors::MultiThreadedExecutor exe(rclcpp::executor::ExecutorArgs(), 4);
      |                                                        ^~~~~~~~
make[2]: *** [CMakeFiles/test_vicon2_driver.dir/build.make:63: CMakeFiles/test_vicon2_driver.dir/test/test_vicon2_driver.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/test_vicon2_driver.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
\---
Failed   <<< vicon2_driver [2.71s, exited with code 2]

I then managed to compile by commenting everything related to test_vicon2_driver on the cmake. But then, when I tried to run the driver, I had the following errors:

> [INFO] [launch]: All log files can be found below /home/evbernardes/.ros/log/2021-12-23-16-08-04-012955-evbernardes-Precision-7730-853141
[INFO] [launch]: Default logging verbosity is set to INFO
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<LaunchService._process_one_event() done, defined at /opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py:226> exception=InvalidLaunchFileError('py')>
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 53, in get_launch_description_from_any_launch_file
    return loader(launch_file_path)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/python_launch_file_utilities.py", line 68, in get_launch_description_from_python_launch_file
    return getattr(launch_file_module, 'generate_launch_description')()
  File "/home/evbernardes/ros2_ws/install/vicon2_driver/share/vicon2_driver/launch/vicon2.launch.py", line 43, in generate_launch_description
    driver_node = LifecycleNode(
TypeError: __init__() missing 2 required keyword-only arguments: 'name' and 'namespace'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 228, in _process_one_event
    await self.__process_event(next_event)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_service.py", line 248, in __process_event
    visit_all_entities_and_collect_futures(entity, self.__context))
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 45, in visit_all_entities_and_collect_futures
    futures_to_return += visit_all_entities_and_collect_futures(sub_entity, context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/utilities/visit_all_entities_and_collect_futures_impl.py", line 38, in visit_all_entities_and_collect_futures
    sub_entities = entity.visit(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/action.py", line 108, in visit
    return self.execute(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/actions/include_launch_description.py", line 127, in execute
    launch_description = self.__launch_description_source.get_launch_description(context)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_source.py", line 84, in get_launch_description
    self._get_launch_description(self.__expanded_location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_description_source.py", line 53, in _get_launch_description
    return get_launch_description_from_any_launch_file(location)
  File "/opt/ros/galactic/lib/python3.8/site-packages/launch/launch_description_sources/any_launch_file_utilities.py", line 56, in get_launch_description_from_any_launch_file
    raise InvalidLaunchFileError(extension, likely_errors=exceptions)
launch.invalid_launch_file_error.InvalidLaunchFileError: Caught exception when trying to load file of format [py]: __init__() missing 2 required keyword-only arguments: 'name' and 'namespace'

Ubuntu 20.04 Focal Fossa
ROS2 Galactic

**Comment by fmrico** [comment]
Hi @evbernardes 

Maybe the last commit fixed it...

**Comment by evbernardes** [comment]
> Maybe the last commit fixed it...

Hey there! Thanks for the heads up :)
Sadly I'm not working with Vicon at the moment and the last project is already up and running with ROS1 and Mavros, so it will have to stay like this.

I'll gladly give this another go next time I have to set up something with the mocap system here :)
